library(lubridate)
library(dplyr)
setwd("C:/Users/Victor/OneDrive/Desktop/Coursera/ProgrammingAssignment4/UCI HAR Dataset")
features <- read.table("features.txt", col.names = c("n","functions"))
activities <- read.table("activity_labels.txt", col.names = c("code", "activity"))
subject_test <- read.table("test/subject_test.txt", col.names = "subject")
x_test <- read.table("test/X_test.txt", col.names = features$functions)
y_test <- read.table("test/y_test.txt", col.names = "code")
subject_train <- read.table("train/subject_train.txt", col.names = "subject")
x_train <- read.table("train/X_train.txt", col.names = features$functions)
y_train <- read.table("train/y_train.txt", col.names = "code")
X <- rbind(x_test,x_train)
Y <- rbind(y_test,y_train)
rm(x_test)
rm(x_train)
rm(y_test)
rm(y_train)
subject <- rbind(subject_test,subject_train)
rm(subject_test)
rm(subject_train)
DT <- cbind(subject,X,Y)
DT <- DT %>%
  select(subject,code,contains("mean"),contains("std"))
DT$code <- activities[DT$code,2]
names(DT)[2] = "activity"
names(DT)<-gsub("Acc", "Accelerometer", names(DT))
names(DT)<-gsub("Gyro", "Gyroscope", names(DT))
names(DT)<-gsub("BodyBody", "Body", names(DT))
names(DT)<-gsub("Mag", "Magnitude", names(DT))
names(DT)<-gsub("^t", "Time", names(DT))
names(DT)<-gsub("^f", "Frequency", names(DT))
names(DT)<-gsub("tBody", "TimeBody", names(DT))
names(DT)<-gsub("-mean()", "Mean", names(DT), ignore.case = TRUE)
names(DT)<-gsub("-std()", "STD", names(DT), ignore.case = TRUE)
names(DT)<-gsub("-freq()", "Frequency", names(DT), ignore.case = TRUE)
names(DT)<-gsub("angle", "Angle", names(DT))
names(DT)<-gsub("gravity", "Gravity", names(DT))

mean.DT <- DT %>%
  group_by(activity,subject) %>%
  summarise_all(funs(mean))
write.table(mean.DT, "Submit.txt", row.name=FALSE)
